<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
   "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
   
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />

    <style type="text/css" media="all">@import "/css/default.css";</style>
    <style type="text/css" media="screen">@import "/css/default-screen.css";</style>
    <style type="text/css" media="print">@import "/css/default-print.css";</style>
    <script type="text/javascript" src="/js/default.js"></script>
    <script type="text/javascript" src="/js/ie-transparency.js"></script>

<? foreach ( $cmsPageXML->Meta as $metaInformation ) { ?>
    <meta name="<?= $metaInformation['name']; ?>" content="<?= $metaInformation; ?>" />
<? } ?>

    <title><?= $cmsPageXML['title']; ?> - <?= $cmsSiteXML['title']; ?></title>
  </head>

  <body>
    <div id="wrapper">
    <div id="container">
  
      <div id="header">
        <h1><a href="/">Shopping Cart Demonstration</a></h1>
        <h2>An example of the Margin-Cart and Margin-CMS systems.</h2>
      </div>
  
      <div id="content">

<?= CMS::Indent($childData, 4); ?>

      </div>

      <div id="footer">
        <div id="timing">
          This page was generated in <?= round(CMS::GetMicrotime() - $GLOBALS['pageStartTime'], 4); ?> seconds.
        </div>
        <div id="generator">
          Generated by <a href="http://www.marginsoftware.com/products/mcms" title="Margin Software's own Content Management System!"><b>Margin-CMS</b></a> <?= CMS::Version(); ?> on PHP/<?= phpversion(); ?>.
        </div>
      </div>
      
    </div>
    </div>
  </body>
</html>